In [6]:
import torch
import math
from torch.autograd import Variable

In [17]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4,1])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4,1])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)      

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562, 1.0000])
tensor([0.0000, 0.7071, 1.0000, 0.7071, 0.8415])
tensor([0.0000, 0.7854, 1.5708, 2.3562, 1.0000])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562, 1.0000])
tensor([0.0000, 0.7071, 1.0000, 0.7071, 0.8415])
tensor([0.0000, 0.7071, 1.0000, 0.7071, 0.8415])


In [18]:
y = torch.sin(a)
y

tensor([0.0000, 0.7071, 1.0000, 0.7071, 0.8415])

In [19]:
y = torch.cos(a)
y

tensor([ 1.0000e+00,  7.0711e-01, -4.3711e-08, -7.0711e-01,  5.4030e-01])

In [20]:
y = torch.tan(a)
y

tensor([ 0.0000e+00,  1.0000e+00, -2.2877e+07, -1.0000e+00,  1.5574e+00])

In [21]:
cot=1/(torch.tan(a))
cot

tensor([        inf,  1.0000e+00, -4.3711e-08, -1.0000e+00,  6.4209e-01])

In [22]:
cosec=1/(torch.sin(a))
cosec

tensor([   inf, 1.4142, 1.0000, 1.4142, 1.1884])

In [28]:
sec=1/(torch.cos(a))
y = torch.sum(a**2)
y

tensor(9.6359)

In [30]:
print(a.grad)

None


In [31]:
print(a)

tensor([0.0000, 0.7854, 1.5708, 2.3562, 1.0000])
