In [2]:
import torch
torch.device('cpu')

device(type='cpu')

#MATRIX MULTIPLICATION

In [3]:

a=torch.tensor([[1,2,1],[2,1,3],[1,5,1]],dtype=torch.float32)
b=torch.tensor([[1,2,1],[2,1,3],[1,5,1]],dtype=torch.float32)
c=torch.zeros((3,3),dtype=torch.float32)

In [4]:
ind=2
print(a.size)
for i in range(ind) :
    val1=0.0
    for j in range(ind):
        val1=torch.dot(a[i,:],b[:,j])
        c[i][j]=val1


<built-in method size of Tensor object at 0x00000214A4AB1A90>


In [5]:
print("Multiplied Matrix:\n",c)

Multiplied Matrix:
 tensor([[ 6.,  9.,  0.],
        [ 7., 20.,  0.],
        [ 0.,  0.,  0.]])


In [6]:
#Inbuilt Method
mul = a.matmul(b)
mul

tensor([[ 6.,  9.,  8.],
        [ 7., 20.,  8.],
        [12., 12., 17.]])

#INVERSE OF A MATRIX

In [7]:
a=torch.tensor([[3,2],[1,1]],dtype=torch.float64)
a

tensor([[3., 2.],
        [1., 1.]], dtype=torch.float64)

In [8]:
m,n=a.shape
m,n

(2, 2)

In [9]:
import numpy as np
Inv = np.identity(n=m)
Inv= torch.tensor(Inv,dtype=torch.float64)
Inv

tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)

In [10]:
mat = np.concatenate((a,Inv),axis=1)
mat =torch.tensor(mat,dtype=torch.float64)
mat

tensor([[3., 2., 1., 0.],
        [1., 1., 0., 1.]], dtype=torch.float64)

In [11]:
for i in range (0,m):
    pivot = mat[i][i]
    row = mat[i]
    mat[i] = row / pivot
    for j in [k for k in range(0,m) if k!=i]:
        mat[j] = mat[j]-mat[i]*mat[j][i]
    inverse = mat[:,m:]

inverse

tensor([[ 1.0000, -2.0000],
        [-1.0000,  3.0000]], dtype=torch.float64)

In [12]:
a=torch.tensor([[3,2],[1,1]],dtype=torch.float64)
a

tensor([[3., 2.],
        [1., 1.]], dtype=torch.float64)

In [13]:
inv = a.inverse()
inv

tensor([[ 1.0000, -2.0000],
        [-1.0000,  3.0000]], dtype=torch.float64)

In [14]:
b=torch.tensor([[1,3,2],[1,1,1],[1,2,3]],dtype=torch.float64)
b

tensor([[1., 3., 2.],
        [1., 1., 1.],
        [1., 2., 3.]], dtype=torch.float64)

In [15]:
b_determinant = torch.det(b)
b_adjoint = torch.adjoint(b)
inv = b_adjoint/b_determinant
inv

tensor([[-0.3333, -0.3333, -0.3333],
        [-1.0000, -0.3333, -0.6667],
        [-0.6667, -0.3333, -1.0000]], dtype=torch.float64)

In [16]:
b.inverse()

tensor([[-0.3333,  1.6667, -0.3333],
        [ 0.6667, -0.3333, -0.3333],
        [-0.3333, -0.3333,  0.6667]], dtype=torch.float64)

In [17]:
import torch

def determinant(matrix):
    a, b, c, d = matrix[0, 0], matrix[0, 1], matrix[1, 0], matrix[1, 1]
    return ((a * d) - (b * c))

mat = torch.tensor([[3,2],[2,1]],dtype=torch.float64)


det = determinant(mat)
adj = torch.adjoint(mat)

print("Determinant: ", det)

inv = adj/det
inv

Determinant:  tensor(-1., dtype=torch.float64)


tensor([[-3., -2.],
        [-2., -1.]], dtype=torch.float64)